const assert=require('node:assert/strict'),{normalizeBbk}=require('../bbk.js');
const now=Date.parse('2026-09-29T12:00:00Z');
const B={id:'mow.test',i18nTitle:{de:'Test'},startDate:'2026-09-01T12:00:00Z',severity:'Minor',type:'Alert'};
assert.strictEqual(normalizeBbk([],now).length,0,'leeres Array');
const r0=normalizeBbk([B],now); assert.strictEqual(r0[0].start,B.startDate,'alter Start bleibt');
const r1=normalizeBbk([{...B,type:'Cancel',expiresDate:'2026-09-30T12:00:00Z'}],now); assert.strictEqual(r1.length,1,'Cancel morgen bleibt');
assert.strictEqual(normalizeBbk([{...B,type:'Cancel',expiresDate:'2026-09-28T12:00:00Z'}],now).length,0,'gestern entfällt');
assert.throws(()=>normalizeBbk({},now),'{} wirft');
assert.throws(()=>normalizeBbk([{}],now),'leeres Objekt wirft');
assert.throws(()=>normalizeBbk([{...B,i18nTitle:{}}],now),'fehlender Titel wirft');
assert.throws(()=>normalizeBbk([{...B,i18nTitle:null}],now),'null Titel wirft');
assert.throws(()=>normalizeBbk([{...B,i18nTitle:{de:''}}],now),'leere String wirft');
assert.throws(()=>normalizeBbk([{...B,expiresDate:'gar'}],now),'ungültig expiresDate wirft');
assert.strictEqual(normalizeBbk([{...B,expiresDate:null}],now).length,1,'null Ablauf bleibt');
assert.throws(()=>normalizeBbk([{...B,startDate:'gar'}],now),'ungültig startDate');
assert.throws(()=>normalizeBbk([{...B,type:'X'}],now),'ungültig type');
assert.throws(()=>normalizeBbk([{...B,id:''}],now),'empty id');
const sev=normalizeBbk([{...B,severity:'constructor'}],now); assert.strictEqual(sev[0].severity,'Unknown','severity Unknown');
const s1={...B,startDate:'2026-09-01T12:00:00Z',i18nTitle:{de:'A'}};
const s2={...B,id:'mow.test2',startDate:'2026-09-10T12:00:00Z',i18nTitle:{de:'B'}};
const sorted=normalizeBbk([s1,s2],now);
assert.strictEqual(sorted[0].id,'mow.test2','Sortierung absteigend');
assert.strictEqual(sorted[1].id,'mow.test','Sortierung zweiter');
console.log('PASS');
